<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Hitung</name>
   <tag></tag>
   <elementGuidId>e5f69f7a-6bc3-4422-bf43-37e4ae1ac40b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hitung_harga_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hitung_harga_button']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>79197bb9-1dfb-4c91-85c4-39a891a74f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hitung_harga_button</value>
      <webElementGuid>e4eb0f16-0cd6-4046-be44-e1d3bb367b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-12 col-md-6 p-0</value>
      <webElementGuid>f60c435e-0785-4dcf-a7a8-48d67507f66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung</value>
      <webElementGuid>ab238c61-59a7-43ba-9d03-fa7be38aace6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hitung_harga_button&quot;)</value>
      <webElementGuid>e79ce7b4-131f-44a5-9a19-7c242c4973c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='hitung_harga_button']</value>
      <webElementGuid>706e8724-ca1d-4b00-9152-55709e48c044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_hitung_harga']/div[2]</value>
      <webElementGuid>b0b5214e-cc35-4da0-b129-610ed2db3e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangka Waktu'])[2]/following::div[1]</value>
      <webElementGuid>bce25771-eece-478f-a8c8-fc67fca0f646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Per Bulan'])[2]/following::div[2]</value>
      <webElementGuid>fa6e1652-f586-4270-a54e-8f5b8220f7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARI PROPERTI'])[1]/preceding::div[3]</value>
      <webElementGuid>48728b6d-4599-410c-a003-d3279acc0981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>045a478b-e5fb-4627-8fcb-89e5e4b15e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'hitung_harga_button' and (text() = 'Hitung' or . = 'Hitung')]</value>
      <webElementGuid>c3c67250-f9e6-4201-aab2-089a2d2b7d31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
